export const baseApiUrl = process.env.NODE_ENV === 'development' ? `http://127.0.0.1:8090/api` : `http://127.0.0.1:8090/api`;

export const authorities = {
    STUDENT_VIEW: "ver_estudante",
    STUDENT_CREATE: "adicionar_estudante",
    STUDENT_DELETE: "eliminar_estudante",
    STUDENT_EDIT: "editar_estudante",
    TEACHER_VIEW: "ver_docente",
    TEACHER_CREATE: "adicionar_docente",
    TEACHER_DELETE: "eliminar_docente",
    TEACHER_EDIT: "editar_docente",
    COURSE_VIEW: "ver_curso",
    COURSE_CREATE: "adicionar_curso",
    COURSE_DELETE: "eliminar_curso",
    COURSE_EDIT: "editar_curso",
    DEPARTMENT_VIEW: "ver_departamento",
    DEPARTMENT_CREATE: "adicionar_departamento",
    DEPARTMENT_DELETE: "eliminar_departamento",
    DEPARTMENT_EDIT: "editar_departamento",
    CLASS_VIEW: "ver_cadeiras",
    CLASS_CREATE: "adicionar_cadeira",
    CLASS_DELETE: "eliminar_cadeira",
    CLASS_EDIT: "editar_cadeira",
    ASSISTANT_CREATE: "adicionar_assistente",
    ASSISTANT_VIEW: "ver_assistente",
    ASSISTANT_DELETE: "eliminar_assistente",
    EVALUATION_CREATE: "adicionar_avaliacao",
    EVALUATION_VIEW: "ver_avaliacao",
    EVALUATION_EDIT: "editar_avaliacao",
    GRADE_SUBMIT: "lancar_nota",
    GRADE_VIEW: "ver_nota",
    GRADE_EDIT: "editar_nota",
    USER_VIEW: "ver_usuario",
    USER_CREATE: "adicionar_usuario",
    USER_DELETE: "eliminar_usuario",
    USER_EDIT: "editar_usuario",
    ROLE_VIEW: "ver_papel",
    ROLE_CREATE: "adicionar_papel",
    ROLE_DELETE: "eliminar_papel",
    ROLE_EDIT: "editar_papel",

}